ViewModels/ChangePasswordUserView.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Itsomax.Module.UserManagement.ViewModels
{
    public class ChangePasswordUserView
    {
        public ChangePasswordUserView()
        {
        }
		[Required]
		[DataType(DataType.Password)]
		public string NewPassword { get; set; }
		[Required]
		[DataType(DataType.Password)]
		[Compare("NewPassword", ErrorMessage = "The password and confirmation password do not match.")]
		[Display(Name = "Confirm password")]
		public string ConfirmPassword { get; set; }
    }
}

Controllers/UserManagementController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Itsomax.Module.Core.Interfaces;
using Itsomax.Module.Core.Models;
using Itsomax.Module.UserCore.Interfaces;
using Itsomax.Module.UserCore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;

//using NToastNotify.Libraries;

namespace Itsomax.Module.UserManagement.Controllers
{
    [Authorize(Policy = "ManageAuthentification")]
    public class UserManagementController : Controller
    {
        private readonly IManageUser _manageUser;
        private readonly SignInManager<User> _signIn;
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<Role> _roleManager;
        private readonly IToastNotification _toastNotification;
        private readonly ILogginToDatabase _logger;

        public UserManagementController(IManageUser manageUser,ICreateMenu createMenu,SignInManager<User> 
                signIn,UserManager<User> user,RoleManager<Role> roleManage, IToastNotification toastNotification,
        ILogginToDatabase logger)
        {
            _manageUser=manageUser;
            _signIn = signIn;
            _userManager = user;
            _roleManager = roleManage;
            _toastNotification = toastNotification;
            _logger = logger;
        }
        //[CheckSessionOut]
        public IActionResult CreateUser()
        {
            var userModel = new CreateUserViewModel
            {
                RolesList = _roleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Value = x.Name,
                    Text = x.Name
                })
            };
            return View(userModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUserPostView(CreateUserViewModel model,params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {

                var res = await _manageUser.CreateUserAsync(model,GetCurrentUserAsync().Result.UserName ,selectedRoles);
                if (res.Succeeded)
                {
                    _toastNotification.AddSuccessToastMessage(res.OkMessage, new ToastrOptions
                    {
                        PositionClass = ToastPositions.TopCenter
                    });
                    return RedirectToAction("ListActiveUsers");
                }
                _toastNotification.AddWarningToastMessage(res.Errors, new ToastrOptions
                {
                    PositionClass = ToastPositions.TopCenter
                });
                model.RolesList = _roleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Value = x.Name,
                    Text = x.Name
                });
                return View(nameof(CreateUser),model);

            }
            return View(nameof(CreateUser),model);
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("Login")]
        public IActionResult LoginView(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("Login")]
        public async Task<IActionResult> LoginView(LoginUserViewModel model ,string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (!ModelState.IsValid) return View(model);
            var res = await _manageUser.UserLoginAsync(model);
            if (res.Succeeded)
            {
                HttpContext.Session.SetString("SessionId",model.UserName.ToUpper());
                return RedirectToLocal(returnUrl);
            }

            _toastNotification.AddWarningToastMessage("Invalid user or password, please try again",
                new ToastrOptions
                {
                    PositionClass = ToastPositions.TopCenter,
                    
                });
            return View(model);
        }
        [HttpGet("/get/user/{Id}")]
        public async Task<IActionResult> EditUserView(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.FindByIdAsync(id.ToString());
            if(user == null)
            {
                return NotFound();
            }
            var locked = await _userManager.IsLockedOutAsync(user);
            var roles = _manageUser.GetUserRolesToSelectListItem(id.Value);
            var editUser = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                RolesList = roles,
                IsLocked = locked,
                IsDeleted = user.IsDeleted
            };
            return View(editUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUserPostView(EditUserViewModel model, params string[] rolesAdd)
        {
            var roles = _manageUser.GetUserRolesToSelectListItem(model.Id);
            if (ModelState.IsValid)
            {
                var res = await _manageUser.EditUserAsync(model,GetCurrentUserAsync().Result.UserName, rolesAdd);
                if (!res.Succeeded)
                {
                    _toastNotification.AddErrorToastMessage(res.Errors, new ToastrOptions
                    {
                        PositionClass = ToastPositions.TopCenter
                    });
                    model.RolesList = roles;
                    return View(nameof(EditUserView), model);
                }

                _toastNotification.AddSuccessToastMessage(res.OkMessage, new ToastrOptions
                {
                    PositionClass = ToastPositions.TopCenter,
                    PreventDuplicates = true
                });
                return RedirectToAction(nameof(ListActiveUsers));
            }
            model.RolesList = roles;
            return View(nameof(EditUserView), model);
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteUserPostView(long? id)
        {
            if(id == null)
            {
                return Json(false);
            }
            else
            {
                var user = await _userManager.FindByIdAsync(id.Value.ToString());

                if(user == null)
                {
                    return Json(false);
                }

                var currentUser = GetCurrentUserAsync().Result;

                if (user != currentUser)
                {
                    try
                    {
                        if(user.IsDeleted)
                        {
                            user.IsDeleted = false;
                            var res = await _userManager.UpdateAsync(user);
                            if (res.Succeeded)
                            {
                                _logger.InformationLog("User " + user.UserName + " disabled succesful", "Disable User",
                                    string.Empty, GetCurrentUserAsync().Result.UserName);
                                return Json(true);

                            }
                            else
                            {
                                _logger.InformationLog("User " + user.UserName + " not disabled succesful",
                                    "Disable User", AddErrorList(res), GetCurrentUserAsync().Result.UserName);
                                return Json(false);
                            }

                        }
                        else
                        {
                            user.IsDeleted = true;
                            var res = await _userManager.UpdateAsync(user);
                            if (res.Succeeded)
                            {
                                _logger.InformationLog("User " + user.UserName + " enabled succesful", "Disable User",
                                    string.Empty, GetCurrentUserAsync().Result.UserName);
                                return Json(true);

                            }
                            else
                            {
                                _logger.InformationLog("User " + user.UserName + " not enabled succesful",
                                    "Disable User", AddErrorList(res), GetCurrentUserAsync().Result.UserName);
                                return Json(false);
                            }
                        }
                        
                    }

                    catch (Exception ex)
                    {
                        var message = ex.Message;
                        _logger.ErrorLog(ex.Message, "Disable User", ex.InnerException.Message,
                            GetCurrentUserAsync().Result.UserName);
                        return Json(false);
                    }
                }
                else
                {
                    _logger.InformationLog("User " + user.UserName + " tried to disable himself", "Disable User",
                        string.Empty, GetCurrentUserAsync().Result.UserName);
                    return Json(false);
                }


            }
        }
        
        [HttpDelete]
        public async Task<IActionResult> LockUserPostView(long? id)
        {
            if(id == null)
            {
                return Json(false);
            }
            else
            {
                var user = await _userManager.FindByIdAsync(id.Value.ToString());
                var locked = await _userManager.IsLockedOutAsync(user);
                if(user == null)
                {
                    return Json(false);
                }

Views/UserManagement/ChangePasswordUserView.cshtml
@model  ChangePasswordUserViewModel

<div class="container-fluid">
    <br />
    <div class="col-lg-12">
        <div class="card card-outline-info">
            <div class="card-header bg-theme">
                <h2 class="m-b-0 text-white">Change Password for User: @Model.UserName</h2>
            </div>
            <form autocomplete="off" class="form-horizontal p-t-20 justify-content-center" asp-controller="UserManagement" asp-action="ChangePasswordUserPostView" method="Post">
                <div class="form-body">
                    <div class="form-group row align-items-center">
                        <div class="col-md-3">
                            <input asp-for="UserId" type="hidden" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label class="col-sm-2 text-right control-label" asp-for="UserName"></label>
                        <div class="col-sm-4">
                            <div class="input-group">
                                <div class="input-group-prepend">

                                </div>
                                <p class="form-control-static">@Model.UserName</p>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="newpassword" class="col-sm-2 text-right control-label" asp-for="NewPassword"></label>
                        <div class="col-sm-4">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">
                                        <i class="ti-lock"></i>
                                    </span>
                                </div>
                                <input id="newpassword" asp-for="NewPassword" class="form-control" />
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <span asp-validation-for="NewPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="confirmpassword" class="col-sm-2 text-right control-label" asp-for="ConfirmPassword"></label>
                        <div class="col-sm-4">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon2">
                                        <i class="ti-lock"></i>
                                    </span>
                                </div>
                                <input id="confirmpassword" asp-for="ConfirmPassword" class="form-control" />
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10 ml-md-auto">
                            <button type="submit" class="btn btn-info waves-effect waves-light">Save</button>
                            <a asp-controller="UserManagement" asp-action="ListActiveUsers" class="btn btn-info waves-effect waves-light">Cancel</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Views/UserManagement/ChangePasswordView.cshtml
@model  ChangePasswordViewModel



<div class="container-fluid">
    <br />
    <div class="col-lg-12">
        <div class="card card-outline-info">
            <div class="card-header bg-theme">
                <h2 class="m-b-0 text-white">Change your password</h2>
            </div>
            <form autocomplete="off" class="form-horizontal p-t-20 justify-content-center" asp-controller="UserManagement" asp-action="ChangePasswordPostView" method="Post">
                <div class="form-body">
                    <div class="form-group row align-items-center">
                        <label for="currentPassword" class="col-sm-2 text-right control-label" asp-for="CurrentPassword"></label>
                        <div class="col-sm-4">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">
                                        <i class="ti-lock"></i>
                                    </span>
                                </div>
                                <input id="currentPassword" asp-for="CurrentPassword" class="form-control" />
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <span asp-validation-for="CurrentPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="newpassword" class="col-sm-2 text-right control-label" asp-for="NewPassword"></label>
                        <div class="col-sm-4">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon2">
                                        <i class="ti-lock"></i>
                                    </span>
                                </div>
                                <input id="newpassword" asp-for="NewPassword" class="form-control" />
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <span asp-validation-for="NewPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="confirmpassword" class="col-sm-2 text-right control-label" asp-for="ConfirmPassword"></label>
                        <div class="col-sm-4">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon3">
                                        <i class="ti-lock"></i>
                                    </span>
                                </div>
                                <input id="confirmpassword" asp-for="ConfirmPassword" class="form-control" />
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10 ml-md-auto">
                            <button type="submit" class="btn btn-info waves-effect waves-light">Save</button>
                            <a asp-controller="Admin" asp-action="Welcome" class="btn btn-info waves-effect waves-light">Cancel</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/UserManagement/CreateUser.cshtml
@model CreateUserViewModel


<div class="container-fluid">
    <br />
  <div class="row">
      <div class="col-lg-12">
          <div class="card card-outline-info">
              <div class="card-header bg-theme">
                  <h2 class="m-b-0 text-white">Create User</h2>
              </div>
              <div class="card-body">
                  <form autocomplete="off" class="form-horizontal p-t-20" asp-controller="UserManagement" asp-action="CreateUserPostView" method="Post">
                      <h3 class="box-title">User Details</h3>
                      <hr class="m-t-0 m-b-40">
                      <div class="form-group row">
                          <label for="username2" class="col-sm-2 text-right control-label" asp-for="UserName"></label>
                          <div class="col-sm-4">
                              <div class="input-group">
                                  <div class="input-group">
                                      <div class="input-group-prepend">
                                          <span class="input-group-text" id="basic-addon1">
                                              <i class="ti-user"></i>
                                          </span>
                                      </div>
                                      <input asp-for="UserName" class="form-control" id="username2" placeholder="Username" />
                                  </div>
                              </div>
                          </div>
                          <div class="col-sm-6">
                              <span asp-validation-for="UserName" class="text-danger"></span>
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="email" class="col-sm-2 text-right control-label " asp-for="Email"></label>
                          <div class="col-sm-4">
                              <div class="input-group">
                                  <div class="input-group-prepend">
                                      <span class="input-group-text" id="basic-addon2">
                                          <i class="ti-email"></i>
                                      </span>
                                  </div>
                                  <input asp-for="Email" class="form-control" id="email" placeholder="Email" />
                              </div>
                          </div>
                          <div class="col-sm-6">
                              <span asp-validation-for="Email" class="text-danger"></span>
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="password" class="col-sm-2 text-right control-label " asp-for="Password"></label>
                          <div class="col-sm-4">
                              <div class="input-group">
                                  <div class="input-group-prepend">
                                      <span class="input-group-text" id="basic-addon3">
                                          <i class="ti-lock"></i>
                                      </span>
                                  </div>
                                  <input asp-for="Password" class="form-control" id="password" placeholder="Password" />
                              </div>
                          </div>
                          <div class="col-sm-6">
                              <span asp-validation-for="Password" class="text-danger"></span>
                          </div>
                      </div>
                      <div class="form-group row align-items-center">
                          <label for="password2" class="col-sm-2 text-right control-label " asp-for="ConfirmPassword"></label>
                          <div class="col-sm-4">
                              <div class="input-group">
                                  <div class="input-group-prepend">
                                      <span class="input-group-text" id="basic-addon4">
                                          <i class="ti-lock"></i>
                                      </span>
                                  </div>
                                  <input asp-for="ConfirmPassword" class="form-control" id="password2" placeholder="Password" />
                              </div>
                          </div>
                          <div class="col-sm-6">
                              <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                          </div>
                      </div>
                      <h3 class="box-title">Assign Roles</h3>
                      <hr class="m-t-0 m-b-40">
                      <div class="form-group row align-items-center">
                          <div class="col-md-10 ml-md-auto">
                              @foreach (var item in Model.RolesList)
                                {
                                      <div class="checkbox checkbox-info">
                                          <input id="@item.Value" type="checkbox" name="SelectedRoles" value="@item.Value">
                                          <label for="@item.Value">@item.Value</label>
                                      </div>
                               }
                          </div>
                      </div>
                      <h3 class="box-title">Save new user</h3>
                      <hr class="m-t-0 m-b-40">
                      <div class="form-group row">
                          <div class="col-md-10 ml-md-auto">
                              <button type="submit" class="btn btn-info waves-effect waves-light"><i class="fa fa-check"></i> Save</button>
                              <a asp-controller="UserManagement" asp-action="ListActiveUsers" class="btn btn-info waves-effect waves-light">Cancel</a>
                          </div>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>


@section scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Views/UserManagement/LoginView.cshtml
@model LoginUserViewModel
@inject SignInManager<User> SignInManager
@inject GetSettings GetSettings

@{
    Layout=null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login into @GetSettings.SystemTitle()</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mathias Kowoll">
    <!-- Bootstrap -->
    <link href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/pages/login-register-lock.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/colors/default.css" id="theme" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
    <section id="wrapper" class="login-register login-sidebar" style="background-image:url(@GetSettings.SystemLoginImageUrl());">
        <div class="login-box card">
            <div class="card-body">
                <h4 class="card-title text-center">Login into @GetSettings.SystemLoginText()</h4>
                <form autocomplete="off" asp-controller="UserManagement" asp-action="LoginView" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal form-material">
                    <div class="form-group m-t-40">
                        <div class="col-xs-12">
                            <input asp-for="UserName" class="form-control" id="IUsername" placeholder="Username">
                            <span asp-validation-for="UserName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group m-t-40">
                        <div class="col-xs-12">
                            <input asp-for="Password" class="form-control" id="password" placeholder="Password">
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group  m-t-40" >
                        <div class="col-md-12">
                            <div class="checkbox checkbox-primary pull-left p-t-0">
                                <input id="checkbox-signup" type="checkbox">
                                <label for="checkbox-signup"> Remember me </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-center m-t-20">
                        <div class="col-xs-12">
                            <button class="btn btn-info btn-lg btn-block text-uppercase btn-rounded" type="submit">Log In</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    
    <script src="~/assets/plugins/jquery/jquery.min.js"></script>
    <script src="~/assets/plugins/popper/popper.min.js"></script>
    <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

@await Component.InvokeAsync("NToastNotify")

</body>
</html>