Controllers/RoleManagementController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Itsomax.Data.Infrastructure.Data;
using Itsomax.Module.Core.Data;
using Itsomax.Module.Core.Extensions.CommonHelpers;
using Itsomax.Module.Core.Interfaces;
using Itsomax.Module.Core.Models;
using Itsomax.Module.UserCore.Interfaces;
using Itsomax.Module.UserCore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;

//using NToastNotify.Libraries;


namespace Itsomax.Module.UserManagement.Controllers
{
    [Authorize(Policy = "ManageAuthentification")]
    public class RoleManagementController : Controller
    {
        private readonly RoleManager<Role> _roleManager;
        private readonly UserManager<User> _userManager;
        private readonly ItsomaxDbContext _context;
        private readonly IRepository<SubModule> _subModule;
        private readonly IRepository<Role> _role;
        private readonly IManageUser _manageUser;
        private readonly IToastNotification _toastNotification;
        private readonly ILogginToDatabase _logger;


        public RoleManagementController(RoleManager<Role> roleManager,ItsomaxDbContext context,
                                    IRepository<SubModule> subModule,IManageUser manageUser, IRepository<Role> role,
                                    IToastNotification toastNotification, ILogginToDatabase logger, 
            UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _context = context;
            _subModule = subModule;
            _manageUser = manageUser;
            _role = role;
            _toastNotification = toastNotification;
            _logger = logger;
            _userManager = userManager;
        }

        public IActionResult CreateRole()
        {
            var modulelist = new CreateRoleViewModel();
            try
            {
                
                modulelist.ModuleList = _subModule.Query().Where(x => x.ActiveSubModule).Select(x => new SelectListItem
                {
                    Value = x.Name,
                    Text = StringHelperClass.CamelSplit(x.Name)
                });
                return View(modulelist);
            }
            catch(Exception ex)
            {
                _toastNotification.AddSuccessToastMessage("Error ocurrerd: "+ex, new ToastrOptions
                {
                    PositionClass = ToastPositions.TopCenter
                });
                _logger.ErrorLog(ex.Message, "Create Role", ex.InnerException.Message,
                    GetCurrentUserAsync().Result.UserName);
                return RedirectToAction("ListRoles");
            }
            
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateRolePostView(CreateRoleViewModel model, params string[] selectedModules)
        {
            Role role = new Role
            {
                Name = model.RoleName
            };

            if(ModelState.IsValid)
            {
                var res = _roleManager.CreateAsync(role).Result;
                if (res.Succeeded)
                {
                    try
                    {
                        foreach (var item in selectedModules)
                        {
                            var mod = _subModule.Query().Where(x => x.ActiveSubModule).FirstOrDefault(x => x.Name.Contains(item));
                            if (mod != null)
                            {
                                ModuleRole modrole = new ModuleRole
                                {
                                    RoleId = role.Id,
                                    SubModuleId = mod.Id
                                };
                                _context.Set<ModuleRole>().AddRange(modrole);
                            }

                            _context.SaveChanges();
                        }
                        _toastNotification.AddSuccessToastMessage("Role: " + model.RoleName + " created succesfully", 
                            new ToastrOptions
                        {
                            PositionClass = ToastPositions.TopCenter
                        });
                        _logger.InformationLog("Role" + role.Name + " created succesfully", "Create Role", string.Empty,
                            GetCurrentUserAsync().Result.UserName);
                        return RedirectToAction("ListRoles");
                    }
                    catch (Exception ex)
                    {
                        _toastNotification.AddErrorToastMessage("Could not create role: " + model.RoleName, 
                            new ToastrOptions
                        {
                            PositionClass = ToastPositions.TopCenter
                        });
                        _logger.InformationLog(ex.Message, "Create Role", ex.InnerException.Message,
                            GetCurrentUserAsync().Result.UserName);
                        return View(nameof(CreateRole), model);
                    }

                }
                _toastNotification.AddErrorToastMessage("Could not create role: " + model.RoleName, 
                    new ToastrOptions
                    {
                        PositionClass = ToastPositions.TopCenter
                    });
                _logger.InformationLog("Could not create role: " + model.RoleName, "Create Role", string.Empty,
                    GetCurrentUserAsync().Result.UserName);
                return View(nameof(CreateRole), model);
            }

            return View(nameof(CreateRole), model);
        }
        [HttpGet]
        [Route("/get/all/active/roles/json/")]
        public JsonResult ListRolesView()
        {

            try
            {
                var roles = _role.Query().ToList().Select(x => new RoleListViewModel
                {
                    Id = x.Id,
                    RoleName = x.Name
                });
                return Json(roles);
            }
            catch(Exception ex)
            {
                _toastNotification.AddErrorToastMessage("An error occurred", new ToastrOptions
                {
                    PositionClass = ToastPositions.TopCenter
                });
                _logger.InformationLog(ex.Message, "ListRolesView", ex.InnerException.Message,
                    GetCurrentUserAsync().Result.UserName);
                return Json(false);
            }
            
        }

        public IActionResult ListRoles()
        {
            return View();
        }

        [HttpGet("/get/role/{Id}")]
        public IActionResult EditRoleView(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = _roleManager.FindByIdAsync(id.Value.ToString()).Result;
            var subModules = _manageUser.GetRoleModulesToSelectListItem(role.Id);
            var roleEdit = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name,
                ModuleList = subModules,

            };

            return View(roleEdit);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditRolePostView(EditRoleViewModel model,params string[] selectedModules)
        {
            if (ModelState.IsValid)
            {
                var res = _manageUser.EditRole(model,GetCurrentUserAsync().Result.UserName, selectedModules).Result;
                if (res.Succeeded)
                {
                    _toastNotification.AddSuccessToastMessage(res.OkMessage, new ToastrOptions()
                    {
                        PositionClass = ToastPositions.TopCenter
                    });
                    return RedirectToAction("ListRoles");
                }
                else
                {
                    _toastNotification.AddErrorToastMessage(res.Errors, new ToastrOptions()
                    {
                        PositionClass = ToastPositions.TopCenter
                    });
                    return Redirect("/get/role/"+model.Id);
                }

               
            }
            _toastNotification.AddErrorToastMessage("Could not edit role: " + model.RoleName, new ToastrOptions
            {
                PositionClass = ToastPositions.TopCenter
            });
            return View(nameof(EditRoleView),model);

        }

        [HttpDelete]
        public async Task<IActionResult> DeleteRoleView(int? id)
        {
            if(id == null)
            {
                return Json(false);
            }

            var role = await _roleManager.FindByIdAsync(id.Value.ToString());
            var res = await _roleManager.DeleteAsync(role);
            if (res.Succeeded)
            {
                _logger.InformationLog("Role " + role.Name + " deleted succesfully", "Delete Role", string.Empty,
                    GetCurrentUserAsync().Result.UserName);
                return Json(true);
            }

            _logger.InformationLog("Role " + role.Name + " not deleted succesfully", "Delete Role", AddErrorList(res),
                GetCurrentUserAsync().Result.UserName);
            return Json(false);
        }

        #region Helpers

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        private string AddErrorList(IdentityResult result)
        {
            var errorList = string.Empty;
            foreach (var error in result.Errors)
            {
                errorList = errorList + " " + error.Description;
            }
            return errorList;
        }

        private Task<User> GetCurrentUserAsync()
        {

Views/RoleManagement/CreateRole.cshtml
@model CreateRoleViewModel

<div class="container-fluid">
    <br />
    <div class="row">
        <div class="col-lg-12">
            <div class="card card-outline-info">
                <div class="card-header bg-theme">
                    <h2 class="m-b-0 text-white">Create Role</h2>
                </div>
                <div class="card-body">
                    <form autocomplete="off" class="form-horizontal p-t-20 justify-content-center" asp-controller="RoleManagement" asp-action="CreateRolePostView" method="Post">
                        <div class="form-body">
                            <h3 class="box-title">Role Details</h3>
                            <hr class="m-t-0 m-b-40">
                            <div class="form-group row align-items-center">
                                <label class="col-sm-2 text-right control-label" asp-for="RoleName"></label>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">
                                                <i class="ti-user"></i>
                                            </span>
                                        </div>
                                        <input asp-for="RoleName" class="form-control" id="rolename2" placeholder="Role Name" />
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <span asp-validation-for="RoleName" class="text-danger"></span>
                                </div>
                            </div>
                            <h3 class="box-title">Assign Modules</h3>
                            <hr class="m-t-0 m-b-40">
                            <div class="form-group row align-items-center">
                                <div class="col-md-10 ml-md-auto">
                                    @foreach (var item in Model.ModuleList)
                                    {
                                        <div class="checkbox checkbox-info">
                                            <input id="@item.Value" type="checkbox" name="SelectedModules" value="@item.Value">
                                            <label for="@item.Value">@item.Text</label>
                                        </div>
                                    }
                                </div>
                            </div>
                            <h3 class="box-title">Save new role</h3>
                            <hr class="m-t-0 m-b-40">
                            <div class="form-group row">
                                <div class="col-md-10 ml-md-auto">
                                    <button type="submit" class="btn btn-info waves-effect waves-light"><i class="fa fa-check"></i> Save</button>
                                    <a asp-controller="RoleManagement" asp-action="ListRoles" class="btn btn-info waves-effect waves-light">Cancel</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Views/RoleManagement/EditRoleView.cshtml
@model EditRoleViewModel

<div class="container-fluid">
    <br />
    <div class="row">
        <div class="col-lg-12">
            <div class="card card-outline-info">
                <div class="card-header bg-theme">
                    <h2 class="m-b-0 text-white">Edit Role</h2>
                </div>
                <div class="card-body">
                    <form autocomplete="off" class="form-horizontal p-t-20 justify-content-center" asp-controller="RoleManagement" asp-action="EditRolePostView" method="Post">
                        <div class="form-body">
                            <h3 class="box-title">Role Details</h3>
                            <hr class="m-t-0 m-b-40">
                            <div class="form-group row align-items-center">
                                <input asp-for="Id" type="hidden" class="form-control" />
                            </div>
                            <div class="form-group row align-items-center">
                                <label for="rolename2" class="col-sm-2 text-right control-label " asp-for="RoleName"></label>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">
                                                <i class="ti-user"></i>
                                            </span>
                                        </div>
                                        <input asp-for="RoleName" class="form-control" id="rolename2" placeholder="Role Name" />
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <span asp-validation-for="RoleName" class="text-danger"></span>
                                </div>
                            </div>
                            <h3 class="box-title">Assign Modules</h3>
                            <hr class="m-t-0 m-b-40">
                            <div class="form-group row align-items-center">
                                <div class="col-md-10 ml-md-auto">
                                    @foreach (var item in Model.ModuleList)
                                    {
                                        <div class="checkbox checkbox-info">
                                            <input id="@item.Value" type="checkbox" name="SelectedModules" value="@item.Value" checked="@item.Selected">
                                            <label for="@item.Value">@item.Value</label>
                                        </div>
                                    }
                                </div>
                            </div>
                            <h3 class="box-title">Save edited role</h3>
                            <hr class="m-t-0 m-b-40">
                            <div class="form-group row">
                                <div class="col-md-10 ml-md-auto">
                                    <button type="submit" class="btn btn-info waves-effect waves-light"><i class="fa fa-check"></i> Save</button>
                                    <a asp-controller="RoleManagement" asp-action="ListRoles" class="btn btn-info waves-effect waves-light">Cancel</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Views/RoleManagement/ListRoles.cshtml
<div class="container-fluid">
    <div class="col-xs-12">
        <br />
        <div class="card card-outline-info">
            <div class="card-header bg-theme">
                <h2 class="m-b-0 text-white">All active roles</h2>
            </div>
            <div class="card-body">
                <div id='events'></div>
                <table id="roles" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>RoleName</th>
                        </tr>
                    </thead>
                </table>
                <br />
                <a asp-controller="RoleManagement" asp-action="CreateRole" class="btn btn-info waves-effect waves-light">Create Role</a>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="https://cdn.datatables.net/select/1.2.2/js/dataTables.select.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
    <script>
        $(document).ready(function() {
                var table =$('#roles').DataTable({
                    dom: 'Bfrtlip',
                    ajax: {
                        url: '/get/all/active/roles/json/',
                        dataSrc: ''
                    },
                    "columns": [
                        { "data": "id" },
                        { "data": "roleName" }
                    ],
                    paging: true,
                    lengthChange: true,
                    searching: false,
                    ordering: true,
                    info: true,
                    autoWidth: false,
                    columnDefs: [
                    {
                        targets: [ 0 ],
                        visible: false,
                        searchable: false
                    }
                    ],
                    select: {
                            style: 'single'
                        },
                    buttons: [
                            {
                                text: 'Delete',
                                action: function (e, dt, node, config) {
                                    var rowData = dt.row({ selected: true }).data();

                                    if(rowData == null)
                                    {
                                            $.alert({
                                                title: 'No role selected!',
                                                content: 'No role has been selected, to continue please select a role.'
                                            });
                                    }
                                    else
                                    {
                                        $.confirm({
                                            title: 'Delete role',
                                            content: 'Are you sure do you want to delete: ' + rowData.roleName+'?',
                                            buttons: {
                                                        confirm: function () {
                                                            $.ajax({
                                                                url: '/RoleManagement/DeleteRoleView/'+rowData.id,
                                                                type: 'DELETE',
                                                                success: function (obj) {
                                                                    toastr.success('', 'Role: ' + rowData.roleName + ' deleted succesfully', { positionClass: 'toast-top-center' });
                                                                    table.ajax.reload();
                                                                },
                                                                error: function (obj) {
                                                                    toastr.error('', 'Role: ' + rowData.roleName + ' could not be deleted', { positionClass: 'toast-top-center' });
                                                                    table.ajax.reload();
                                                                }
                                                            });
                                                        },
                                                        cancel: function () {
                                                            table.ajax.reload();
                                                        }
                                        }
                                        });
                                    }
                                },
                                enabled: false
                            },
                            {
                                text: 'Edit',
                                action: function (e, dt, node, config) {
                                    var rowData = dt.row({ selected: true }).data();
                                    if(rowData == null)
                                    {
                                        $.alert({
                                            title: 'No user selected!',
                                            content: 'No user has been selected, to continue please select a role.'
                                        });
                                    }
                                    else {
                                        window.location.href = '/get/role/' + rowData.id;
                                    }
                                },
                                enabled: false
                            }
                        ]
                    });
                    table.on( 'select', function () {
                        var selectedRows = table.rows( { selected: true } ).count();
                        table.button( 0 ).enable( selectedRows == 1 );
                        table.button( 1 ).enable( selectedRows == 1 );
                    } );
                    table.on( 'deselect',function() {
                        //var unselectedRows = table.rows( {selected: false} ).count();
                        table.button( 0 ).disable();
                        table.button( 1 ).disable();
                    });
        });
    </script>
}